export default types = {
 
//  Country Page  
    API_GET_TOP_NEWS_BY_COUNTRY_WITH_CATEGORY : "API_GET_TOP_NEWS_BY_COUNTRY_WITH_CATEGORY",                // FIRST OF COUNTRY 

// Home Page Category
    API_GET_GENERAL_CATEGORY : "API_GET_GENERAL_CATEGORY",
    API_GET_BUSINESS_CATEGORY : "API_GET_BUSINESS_CATEGORY",
    API_GET_ENTERTAINMENT_CATEGORY : "API_GET_ENTERTAINMENT_CATEGORY",
    API_GET_SPORTS_CATEGORY : "API_GET_SPORTS_CATEGORY",
    API_GET_HEALTH_CATEGORY : "API_GET_HEALTH_CATEGORY",
    API_GET_SCIENCE_CATEGORY : "API_GET_SCIENCE_CATEGORY",
    API_GET_TECHNOLOGY_CATEGORY : "API_GET_TECHNOLOGY_CATEGORY",


//SOURCE
    API_GET_SOURCE_DETAILS : "API_GET_SOURCE_DETAILS",
    

//Clear Data
    API_GET_CLEAR_DATA : "API_GET_CLEAR_DATA"

}