export default types = {
    API_GET_NEWS_FEED : "API_GET_NEWS_FEED",
    API_SET_NEWS_FEED : "API_SET_NEWS_FEED",
    API_GET_SEARCH_NEWS : "API_GET_SEARCH_NEWS",


//TOP HEADING
    API_GET_TOP_HEADLINES : "API_GET_TOP_HEADLINES",
    API_GET_TOP_NEWS_BY_COUNTRY : "API_GET_TOP_NEWS_BY_COUNTRY",                // FIRST OF COUNTRY 
    API_GET_TOP_NEWS_BY_COUNTRY_WITH_CATEGORY : "API_GET_TOP_NEWS_BY_COUNTRY_WITH_CATEGORY",                // FIRST OF COUNTRY 
    API_GET_TOP_NEWS_BY_CATEGORY : "API_GET_TOP_NEWS_BY_CATEGORY", 
                 // FIRST OF CATEGORY
    API_GET_TOP_NEWS_BY_SOURCE : "API_GET_TOP_NEWS_BY_SOURCE",                  // FIRST OF SOURCE
    
//COUNTRY
    API_GET_COUNTRY_NEWS : "API_GET_COUNTRY_NEWS_BY_CATEGORY",
    API_GET_COUNTRY_NEWS_BY_CATEGORY : "API_GET_COUNTRY_NEWS_BY_CATEGORY",



    

// CATEGORY :
    API_GET_CATEGORY_NEWS : "API_GET_CATEGORY_NEWS",
    API_GET_CATEGORY_NEWS_BY_COUNTRY : "API_GET_CATEGORY_NEWS_BY_COUNTRY",
    API_GET_CATEGORY_NEWS_BY_LANGUAGE : "API_GET_CATEGORY_NEWS_BY_LANGUAGE",


// Home Page Category
    API_GET_GENERAL_CATEGORY : "API_GET_GENERAL_CATEGORY",
    API_GET_BUSINESS_CATEGORY : "API_GET_BUSINESS_CATEGORY",
    API_GET_ENTERTAINMENT_CATEGORY : "API_GET_ENTERTAINMENT_CATEGORY",
    API_GET_SPORTS_CATEGORY : "API_GET_SPORTS_CATEGORY",
    API_GET_HEALTH_CATEGORY : "API_GET_HEALTH_CATEGORY",
    API_GET_SCIENCE_CATEGORY : "API_GET_SCIENCE_CATEGORY",
    API_GET_TECHNOLOGY_CATEGORY : "API_GET_TECHNOLOGY_CATEGORY",


//SOURCE
    API_GET_SOURCE_NEWS_BY_COUNRTY : "API_GET_SOURCE_NEWS_BY_COUNRTY",
    API_GET_SOURCE_NEWS_BY_CATEGORY : "API_GET_SOURCE_NEWS_BY_CATEGORY",
    API_GET_SOURCE_NEWS_BY_ : "API_GET_SOURCE_NEWS_BY_CATEGORY",


//Clear Data
    API_GET_CLEAR_DATA : "API_GET_CLEAR_DATA"

}